Remove unread component
Fixes error:

`error TS6133: "Link" is declared but its value is never read.`

Signed-off-by: Nathen Harvey <nathenharvey@google.com>